# Generated by Django 3.2.13 on 2023-08-22 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Post')),
                ('summary', models.CharField(max_length=200, verbose_name='Resumo do Post')),
                ('text', models.TextField(verbose_name='Texto do Post')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagem do Post')),
                ('main_post', models.BooleanField(default=False, verbose_name='Post Principal')),
                ('date_post', models.DateTimeField(blank=True, null=True, verbose_name='Data do Post')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Criador do Post')),
            ],
        ),
    ]
