# Generated by Django 3.2.13 on 2023-02-02 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_referencias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referencias',
        ),
    ]
